openapi: 3.0.0

components:
  responses:
    search_get:
      description: The request has succeeded
      content:
        application/json:
          schema:
            type: object
            title: SearchGetResponse
            properties:
              data:
                type: object
                title: Data
                properties:
                  created_date:
                    type: string
                    pattern: YYYY-MM-DD HH:MM:SS
                    example: "2019-08-07 07:24:35"
                  is_tracked:
                    type: integer
                    example: 1
                  search:
                    type: object
                    title: Search
                    properties:
                      filters:
                        type: array
                        items:
                          anyOf:
                            - "$ref": "../../definitions.yaml#/definitions/response_search_case_status"
                            - "$ref": "../../definitions.yaml#/definitions/response_search_case_type"
                            - "$ref": "../../definitions.yaml#/definitions/response_search_jurisdiction_v3"
                            - "$ref": "../../definitions.yaml#/definitions/response_search_filing_date_range"
                            - "$ref": "../../definitions.yaml#/definitions/response_search_dollar_amount_range"
                      items_per_page:
                        description: Request data will be returned.
                        type: integer
                        example: 5
                      page:
                        description: Request data will be returned.
                        type: integer
                        example: 1
                      max_result:
                        type: integer
                        example: 1000
                      query:
                        "$ref": "../../definitions.yaml#/definitions/response_search_query"
                      sort_field:
                        type: string
                        enum:
                          - filing_date_ts
                          - last_updated_ts
                          - weight_sum
                        example: weight_sum
                      sort_by:
                        type: string
                        enum:
                          - desc
                          - asc
                        example: desc
                  search_id:
                    type: integer
                    example: 1808
                  search_name:
                    type: string
                    example: "test"
                  tracking_days:
                    type: array
                    items:
                      type: string
                      enum:
                        - monday
                        - tuesday
                        - wednesday
                        - thursday
                        - friday
                        - saturday
                        - sunday
                      example: ["monday", "tuesday"]
                  tracking_time:
                    type: string
                    example: "11:24"
                  updated_date:
                    type: string
                    pattern: YYYY-MM-DD HH:MM:SS
                    example: "2019-08-07 07:24:35"
              message:
                type: string
                example: "Search Found"
              status:
                type: string
                example: "success"
              type:
                type: string
                example: null
