openapi: 3.0.0

components:
  responses:
    root_node:
      description: The request has succeeded
      content:
        application/json:
          schema:
            "$ref": "../../definitions.yaml#/definitions/filter_leaf_node"
          examples:
            JURISDICTION:
              value:
                [
                {
                  "additional_data": null,
                  "child_count": 2,
                  "id": 1,
                  "internal_data": {
                    "hide": false
                  },
                  "level": 1,
                  "name": "Federal",
                  "sort_order": 6
                },
                {
                  "additional_data": null,
                  "child_count": 51,
                  "id": 2,
                  "internal_data": {
                    "hide": false
                  },
                  "level": 1,
                  "name": "State",
                  "sort_order": 7
                },
                {
                  "additional_data": null,
                  "child_count": 1,
                  "id": 3,
                  "internal_data": {
                    "hide": true
                  },
                  "level": 1,
                  "name": "Not Yet Classified",
                  "sort_order": 2372
                }
                ]
            CASE_TYPE:
              value:
                [
                {
                  "additional_data": null,
                  "child_count": 18,
                  "id": 8,
                  "internal_data": {
                    "hide": false
                  },
                  "level": 1,
                  "name": "Civil",
                  "sort_order": 1982
                },
                {
                  "additional_data": null,
                  "child_count": 1,
                  "id": 9,
                  "internal_data": {
                    "hide": false
                  },
                  "level": 1,
                  "name": "Criminal",
                  "sort_order": 2194
                },
                {
                  "additional_data": null,
                  "child_count": 1,
                  "id": 10,
                  "internal_data": {
                    "hide": false
                  },
                  "level": 1,
                  "name": "Not Classified By Court",
                  "sort_order": 2197
                },
                {
                  "additional_data": null,
                  "child_count": 1,
                  "id": 11,
                  "internal_data": {
                    "hide": false
                  },
                  "level": 1,
                  "name": "Not Yet Classified",
                  "sort_order": 2198
                }
                ]
            CASE_STATUS:
              value:
                [
                {
                  "additional_data": null,
                  "child_count": 5,
                  "id": 25,
                  "internal_data": {
                    "hide": false
                  },
                  "level": 1,
                  "name": "Pending",
                  "sort_order": 2203
                },
                {
                  "additional_data": null,
                  "child_count": 5,
                  "id": 23,
                  "internal_data": {
                    "hide": false
                  },
                  "level": 1,
                  "name": "Disposed",
                  "sort_order": 2209
                },
                {
                  "additional_data": null,
                  "child_count": 5,
                  "id": 24,
                  "internal_data": {
                    "hide": false
                  },
                  "level": 1,
                  "name": "Other",
                  "sort_order": 2215
                },
                {
                  "additional_data": null,
                  "child_count": 1,
                  "id": 26,
                  "internal_data": {
                    "hide": false
                  },
                  "level": 1,
                  "name": "Not Classified By Court",
                  "sort_order": 2221
                },
                {
                  "additional_data": null,
                  "child_count": 1,
                  "id": 27,
                  "internal_data": {
                    "hide": false
                  },
                  "level": 1,
                  "name": "Not Yet Classified",
                  "sort_order": 2222
                }
                ]
            DOCKET_TAG:
              value:
                [
                {
                  "additional_data": null,
                  "child_count": 17,
                  "id": 1024,
                  "internal_data": {
                    "hide": false
                  },
                  "level": 1,
                  "name": "Motion",
                  "sort_order": 2306
                }
                ]